name: autofix.ci

on: [pull_request]

jobs:
  autofix:
    uses: sxzz/workflows/.github/workflows/autofix.yml@v1
    with:
      command: pnpm lint:fix && pnpm build
    permissions:
      contents: read